# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incurred', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Charge_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Charge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=3)),
                ('rate', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(default='Unname Trip', max_length=50)),
                ('users', models.CharField(default='No one', max_length=50)),
                ('output_url', models.URLField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('trip', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Trip'),
        ),
        migrations.AddField(
            model_name='charge',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Trip'),
        ),
    ]
