# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip',
            new_name='trip_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
