# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0006_auto_20170503_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='traveler_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
