# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0009_trip_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_id',
        ),
        migrations.AlterField(
            model_name='trip',
            name='profile_pic',
            field=models.URLField(default='https://unsplash.it/200/200/?random'),
        ),
    ]
