# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0010_auto_20170504_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time_created',
        ),
        migrations.AddField(
            model_name='trip',
            name='time_of_trip',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='profile_pic',
            field=models.URLField(default='https://unsplash.it/360/200/?random'),
        ),
    ]
