# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0011_auto_20170504_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='output_url',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
