# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0012_auto_20170504_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='authorized_viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
