# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0013_trip_authorized_viewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='time_of_trip',
            new_name='trip_start',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='authorized_viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
