# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0014_auto_20170505_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
