# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0015_auto_20170505_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=50)),
                ('segment_start', models.DateField(blank=True)),
                ('segment_end', models.DateField(blank=True)),
                ('segment_lon', models.FloatField()),
                ('segment_lat', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Segment_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_name', models.CharField(max_length=50)),
                ('sd_img', models.URLField(blank=True)),
                ('sd_description', models.TextField(blank=True)),
                ('sd_lon', models.FloatField(blank=True)),
                ('sd_lat', models.FloatField(blank=True)),
                ('sd_time', models.DateTimeField(blank=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.Segment')),
            ],
        ),
    ]
