# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0016_segment_segment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='segment_album',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_img',
            field=models.URLField(blank=True),
        ),
    ]
