# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0019_auto_20170525_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment_detail',
            name='sd_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment_detail',
            name='sd_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
