# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0020_auto_20170525_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment_detail',
            name='sd_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
