# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 05:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0023_auto_20170528_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
