# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0026_auto_20170606_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_album',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_img',
            field=models.URLField(blank=True),
        ),
    ]
