# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0027_auto_20170606_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
