# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0028_trip_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 53, 34, 911000)),
        ),
    ]
