# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 05:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0032_trip_profile_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='profile_svg',
        ),
        migrations.AddField(
            model_name='trip',
            name='profile_misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
