# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 05:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import splitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0033_auto_20170629_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='charges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=splitter.models.charge_json_default),
        ),
        migrations.AlterField(
            model_name='trip',
            name='profile_pic',
            field=models.URLField(default='https://unsplash.it/200/300?image=1039'),
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
