# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0034_auto_20170707_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='charges',
            new_name='accounting',
        ),
    ]
